In [44]:
!pip install mp-api --upgrade
import numpy as np
from mp_api.client import MPRester
#from pymatgen.ext.matproj import MPRester
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import matplotlib.image as img
from pymatgen.ext.matproj import MPRester
from IPython.display import Image
from pymatgen.core.operations import SymmOp
from pprint import pprint


Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip


In [62]:
with MPRester("MykrkEqBZ7EQ2VUWndzndDME88749Z5b") as m:
    structure = m.get_structure_by_material_id("mp-961706")

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [57]:
# Visualisation
view = quick_view(structure)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [53]:
# Symétries de la molécule
sym = SpacegroupAnalyzer(structure).get_symmetry_operations()

#Différentes opérations de symétries
S1=sym[14]; S2=sym[5]; S3=sym[47]

#Coordonées initiales des atomes choisis
Ti=[0.0,0.0,0.5]
Si=[0.0, 0.0, 0.0]
Pt=[0.25, 0.25, 0.25]

Ti_sym=S1.operate(Ti);
Si_sym=S2.operate(Si);
Pt_sym=S3.operate(Pt);

print(sym[14]);print(sym[5]); #
print(sym[47])


Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
Rot:
[[ 0.  0.  1.]
 [-1. -1. -1.]
 [ 1.  0.  0.]]
tau
[0. 0. 0.]
Rot:
[[ 0.  1.  0.]
 [-1. -1. -1.]
 [ 1.  0.  0.]]
tau
[0. 0. 0.]


In [60]:
print("Opération de symétrie 1: \n")
print("L'atome de départ est le Ti et a comme coordonnées: {}\n".format(Ti))
print("On lui applique une symétrie de plan miroir (z,y,x) :\n")
print(S1.rotation_matrix, "*", Ti, '+', S1.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Ti_sym))
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 15 {atomno=1}")

Opération de symétrie 1: 

L'atome de départ est le Ti et a comme coordonnées: [0.0, 0.0, 0.5]

On lui applique une symétrie de plan miroir (z,y,x) :

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] * [0.0, 0.0, 0.5] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [0.5 0.  0. ]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Deuxième opération de symétrie

In [64]:
print("Opération de symétrie 2: \n")
print("L'atome de départ est le Si et a comme coordonnées: {}\n".format(Si))
print("On lui applique une symétrie d'axe 2 ('z,-x-y-z,x') :")
print(S2.rotation_matrix, "*", Si, '+', S2.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Si_sym))
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 6 {atomno=7}")


Opération de symétrie 2: 

L'atome de départ est le Si et a comme coordonnées: [0.0, 0.0, 0.0]

On lui applique une symétrie d'axe 2 ('z,-x-y-z,x') :
[[ 0.  0.  1.]
 [-1. -1. -1.]
 [ 1.  0.  0.]] * [0.0, 0.0, 0.0] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [0. 0. 0.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Troisième opération de symmétrie

In [63]:
print("Opération de symétrie 3: \n")
print("L'atome de départ est le Pt et a comme coordonnées: {}\n".format(Pt))
print("On lui applique une roto-inversion (y,-x-y-z,x) : ")
print(S3.rotation_matrix, "*", Pt, '+', S3.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Pt_sym))
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 2 {atomno=3}")

Opération de symétrie 3: 

L'atome de départ est le Pt et a comme coordonnées: [0.25, 0.25, 0.25]

On lui applique une roto-inversion (y,-x-y-z,x) : 
[[ 0.  1.  0.]
 [-1. -1. -1.]
 [ 1.  0.  0.]] * [0.25, 0.25, 0.25] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [ 0.25 -0.75  0.25]



JsmolView(layout=Layout(align_self='stretch', height='400px'))